// Generated by `pnpm db:types` from the local Supabase schema. Do not edit by hand.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      admin_users: {
        Row: {
          created_at: string
          created_by: string | null
          display_name: string | null
          is_active: boolean
          role: Database["public"]["Enums"]["admin_role"]
          site_id: string
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          display_name?: string | null
          is_active?: boolean
          role?: Database["public"]["Enums"]["admin_role"]
          site_id: string
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          display_name?: string | null
          is_active?: boolean
          role?: Database["public"]["Enums"]["admin_role"]
          site_id?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "admin_users_site_id_fkey"
            columns: ["site_id"]
            isOneToOne: false
            referencedRelation: "sites"
            referencedColumns: ["id"]
          },
        ]
      }
      article_jobs: {
        Row: {
          action_required_at: string | null
          action_required_kind:
            | Database["public"]["Enums"]["action_required_kind"]
            | null
          action_required_message: string | null
          action_required_run_id: string | null
          approved_audit_id: string | null
          approved_draft_id: string | null
          article_id: string | null
          article_type: Database["public"]["Enums"]["article_type"]
          attempt_count: number
          audit_mode: Database["public"]["Enums"]["provider_mode"]
          auto_publish: boolean
          byline_name: string | null
          byline_role: string | null
          category: string | null
          created_at: string
          created_by: string | null
          desired_publish_at: string | null
          failed_stage: Database["public"]["Enums"]["pipeline_stage"] | null
          failure_summary: string | null
          id: string
          image_count: number
          images_mode: Database["public"]["Enums"]["provider_mode"]
          keywords: string[]
          lease_expires_at: string | null
          lease_owner: string | null
          lease_token: string | null
          lock_version: number
          max_attempts: number
          needs_human_stage:
            | Database["public"]["Enums"]["pipeline_stage"]
            | null
          next_attempt_at: string | null
          paused_from_status: Database["public"]["Enums"]["job_status"] | null
          requirements: string | null
          research_mode: Database["public"]["Enums"]["provider_mode"]
          revision_count: number
          site_id: string
          status: Database["public"]["Enums"]["job_status"]
          target_word_count: number | null
          topic: string
          updated_at: string
          writing_mode: Database["public"]["Enums"]["provider_mode"]
        }
        Insert: {
          action_required_at?: string | null
          action_required_kind?:
            | Database["public"]["Enums"]["action_required_kind"]
            | null
          action_required_message?: string | null
          action_required_run_id?: string | null
          approved_audit_id?: string | null
          approved_draft_id?: string | null
          article_id?: string | null
          article_type?: Database["public"]["Enums"]["article_type"]
          attempt_count?: number
          audit_mode: Database["public"]["Enums"]["provider_mode"]
          auto_publish?: boolean
          byline_name?: string | null
          byline_role?: string | null
          category?: string | null
          created_at?: string
          created_by?: string | null
          desired_publish_at?: string | null
          failed_stage?: Database["public"]["Enums"]["pipeline_stage"] | null
          failure_summary?: string | null
          id?: string
          image_count?: number
          images_mode: Database["public"]["Enums"]["provider_mode"]
          keywords?: string[]
          lease_expires_at?: string | null
          lease_owner?: string | null
          lease_token?: string | null
          lock_version?: number
          max_attempts?: number
          needs_human_stage?:
            | Database["public"]["Enums"]["pipeline_stage"]
            | null
          next_attempt_at?: string | null
          paused_from_status?: Database["public"]["Enums"]["job_status"] | null
          requirements?: string | null
          research_mode: Database["public"]["Enums"]["provider_mode"]
          revision_count?: number
          site_id: string
          status?: Database["public"]["Enums"]["job_status"]
          target_word_count?: number | null
          topic: string
          updated_at?: string
          writing_mode: Database["public"]["Enums"]["provider_mode"]
        }
        Update: {
          action_required_at?: string | null
          action_required_kind?:
            | Database["public"]["Enums"]["action_required_kind"]
            | null
          action_required_message?: string | null
          action_required_run_id?: string | null
          approved_audit_id?: string | null
          approved_draft_id?: string | null
          article_id?: string | null
          article_type?: Database["public"]["Enums"]["article_type"]
          attempt_count?: number
          audit_mode?: Database["public"]["Enums"]["provider_mode"]
          auto_publish?: boolean
          byline_name?: string | null
          byline_role?: string | null
          category?: string | null
          created_at?: string
          created_by?: string | null
          desired_publish_at?: string | null
          failed_stage?: Database["public"]["Enums"]["pipeline_stage"] | null
          failure_summary?: string | null
          id?: string
          image_count?: number
          images_mode?: Database["public"]["Enums"]["provider_mode"]
          keywords?: string[]
          lease_expires_at?: string | null
          lease_owner?: string | null
          lease_token?: string | null
          lock_version?: number
          max_attempts?: number
          needs_human_stage?:
            | Database["public"]["Enums"]["pipeline_stage"]
            | null
          next_attempt_at?: string | null
          paused_from_status?: Database["public"]["Enums"]["job_status"] | null
          requirements?: string | null
          research_mode?: Database["public"]["Enums"]["provider_mode"]
          revision_count?: number
          site_id?: string
          status?: Database["public"]["Enums"]["job_status"]
          target_word_count?: number | null
          topic?: string
          updated_at?: string
          writing_mode?: Database["public"]["Enums"]["provider_mode"]
        }
        Relationships: [
          {
            foreignKeyName: "article_jobs_action_required_run_id_id_fkey"
            columns: ["action_required_run_id", "id"]
            isOneToOne: false
            referencedRelation: "provider_runs"
            referencedColumns: ["id", "job_id"]
          },
          {
            foreignKeyName: "article_jobs_approved_audit_id_id_fkey"
            columns: ["approved_audit_id", "id"]
            isOneToOne: false
            referencedRelation: "audits"
            referencedColumns: ["id", "job_id"]
          },
          {
            foreignKeyName: "article_jobs_approved_draft_id_id_fkey"
            columns: ["approved_draft_id", "id"]
            isOneToOne: false
            referencedRelation: "drafts"
            referencedColumns: ["id", "job_id"]
          },
          {
            foreignKeyName: "article_jobs_article_id_fkey"
            columns: ["article_id"]
            isOneToOne: true
            referencedRelation: "articles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "article_jobs_site_id_fkey"
            columns: ["site_id"]
            isOneToOne: false
            referencedRelation: "sites"
            referencedColumns: ["id"]
          },
        ]
      }
      article_slug_aliases: {
        Row: {
          article_id: string
          created_at: string
          created_by: string | null
          site_id: string
          slug: string
        }
        Insert: {
          article_id: string
          created_at?: string
          created_by?: string | null
          site_id: string
          slug: string
        }
        Update: {
          article_id?: string
          created_at?: string
          created_by?: string | null
          site_id?: string
          slug?: string
        }
        Relationships: [
          {
            foreignKeyName: "article_slug_aliases_article_id_fkey"
            columns: ["article_id"]
            isOneToOne: false
            referencedRelation: "articles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "article_slug_aliases_site_id_fkey"
            columns: ["site_id"]
            isOneToOne: false
            referencedRelation: "sites"
            referencedColumns: ["id"]
          },
        ]
      }
      articles: {
        Row: {
          article_type: Database["public"]["Enums"]["article_type"]
          body_markdown: string
          byline_name: string
          byline_role: string | null
          canonical_url: string
          category: string | null
          content_updated_at: string | null
          created_at: string
          excerpt: string
          hero_image: Json | null
          id: string
          meta_description: string
          meta_title: string
          published_at: string
          site_id: string
          slug: string
          source_references: Json
          status: Database["public"]["Enums"]["article_status"]
          title: string
          updated_at: string
          verified_at: string | null
          withdrawn_at: string | null
        }
        Insert: {
          article_type: Database["public"]["Enums"]["article_type"]
          body_markdown: string
          byline_name: string
          byline_role?: string | null
          canonical_url: string
          category?: string | null
          content_updated_at?: string | null
          created_at?: string
          excerpt: string
          hero_image?: Json | null
          id?: string
          meta_description: string
          meta_title: string
          published_at: string
          site_id: string
          slug: string
          source_references?: Json
          status: Database["public"]["Enums"]["article_status"]
          title: string
          updated_at?: string
          verified_at?: string | null
          withdrawn_at?: string | null
        }
        Update: {
          article_type?: Database["public"]["Enums"]["article_type"]
          body_markdown?: string
          byline_name?: string
          byline_role?: string | null
          canonical_url?: string
          category?: string | null
          content_updated_at?: string | null
          created_at?: string
          excerpt?: string
          hero_image?: Json | null
          id?: string
          meta_description?: string
          meta_title?: string
          published_at?: string
          site_id?: string
          slug?: string
          source_references?: Json
          status?: Database["public"]["Enums"]["article_status"]
          title?: string
          updated_at?: string
          verified_at?: string | null
          withdrawn_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "articles_site_id_fkey"
            columns: ["site_id"]
            isOneToOne: false
            referencedRelation: "sites"
            referencedColumns: ["id"]
          },
        ]
      }
      audits: {
        Row: {
          created_at: string
          cycle: number
          draft_id: string
          findings: Json
          id: string
          job_id: string
          prompt_template_id: string | null
          prompt_version: number | null
          provider_run_id: string | null
          review_note: string | null
          reviewed_at: string | null
          reviewed_by: string | null
          schema_version: string
          summary: string | null
          verdict: Database["public"]["Enums"]["audit_verdict"]
          version: number
        }
        Insert: {
          created_at?: string
          cycle: number
          draft_id: string
          findings?: Json
          id?: string
          job_id: string
          prompt_template_id?: string | null
          prompt_version?: number | null
          provider_run_id?: string | null
          review_note?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          schema_version: string
          summary?: string | null
          verdict: Database["public"]["Enums"]["audit_verdict"]
          version: number
        }
        Update: {
          created_at?: string
          cycle?: number
          draft_id?: string
          findings?: Json
          id?: string
          job_id?: string
          prompt_template_id?: string | null
          prompt_version?: number | null
          provider_run_id?: string | null
          review_note?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          schema_version?: string
          summary?: string | null
          verdict?: Database["public"]["Enums"]["audit_verdict"]
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: "audits_draft_id_job_id_fkey"
            columns: ["draft_id", "job_id"]
            isOneToOne: false
            referencedRelation: "drafts"
            referencedColumns: ["id", "job_id"]
          },
          {
            foreignKeyName: "audits_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "article_jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "audits_prompt_template_id_fkey"
            columns: ["prompt_template_id"]
            isOneToOne: false
            referencedRelation: "prompt_templates"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "audits_provider_run_id_job_id_fkey"
            columns: ["provider_run_id", "job_id"]
            isOneToOne: false
            referencedRelation: "provider_runs"
            referencedColumns: ["id", "job_id"]
          },
        ]
      }
      claim_sources: {
        Row: {
          claim_id: string
          created_at: string
          locator: string | null
          relation: Database["public"]["Enums"]["evidence_relation"]
          research_packet_id: string
          source_id: string
        }
        Insert: {
          claim_id: string
          created_at?: string
          locator?: string | null
          relation?: Database["public"]["Enums"]["evidence_relation"]
          research_packet_id: string
          source_id: string
        }
        Update: {
          claim_id?: string
          created_at?: string
          locator?: string | null
          relation?: Database["public"]["Enums"]["evidence_relation"]
          research_packet_id?: string
          source_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "claim_sources_claim_id_research_packet_id_fkey"
            columns: ["claim_id", "research_packet_id"]
            isOneToOne: false
            referencedRelation: "claims"
            referencedColumns: ["id", "research_packet_id"]
          },
          {
            foreignKeyName: "claim_sources_source_id_research_packet_id_fkey"
            columns: ["source_id", "research_packet_id"]
            isOneToOne: false
            referencedRelation: "sources"
            referencedColumns: ["id", "research_packet_id"]
          },
        ]
      }
      claims: {
        Row: {
          as_of_date: string | null
          claim_key: string
          confidence: number | null
          created_at: string
          effective_date: string | null
          entities: string[]
          id: string
          job_id: string
          jurisdiction: string | null
          notes: string | null
          research_packet_id: string
          status: Database["public"]["Enums"]["claim_status"]
          text: string
        }
        Insert: {
          as_of_date?: string | null
          claim_key: string
          confidence?: number | null
          created_at?: string
          effective_date?: string | null
          entities?: string[]
          id?: string
          job_id: string
          jurisdiction?: string | null
          notes?: string | null
          research_packet_id: string
          status?: Database["public"]["Enums"]["claim_status"]
          text: string
        }
        Update: {
          as_of_date?: string | null
          claim_key?: string
          confidence?: number | null
          created_at?: string
          effective_date?: string | null
          entities?: string[]
          id?: string
          job_id?: string
          jurisdiction?: string | null
          notes?: string | null
          research_packet_id?: string
          status?: Database["public"]["Enums"]["claim_status"]
          text?: string
        }
        Relationships: [
          {
            foreignKeyName: "claims_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "article_jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "claims_research_packet_id_job_id_fkey"
            columns: ["research_packet_id", "job_id"]
            isOneToOne: false
            referencedRelation: "research_packets"
            referencedColumns: ["id", "job_id"]
          },
        ]
      }
      drafts: {
        Row: {
          body_markdown: string
          category: string | null
          created_at: string
          created_by: string | null
          excerpt: string
          id: string
          image_briefs: Json
          internal_links: Json
          job_id: string
          meta_description: string | null
          meta_title: string | null
          origin: Database["public"]["Enums"]["draft_origin"]
          parent_draft_id: string | null
          prompt_template_id: string | null
          prompt_version: number | null
          provider_run_id: string | null
          research_packet_id: string
          responds_to_audit_id: string | null
          review_note: string | null
          reviewed_at: string | null
          reviewed_by: string | null
          schema_version: string
          slug: string
          source_refs: Json
          title: string
          validation_errors: Json | null
          validation_status: Database["public"]["Enums"]["artifact_validation"]
          version: number
        }
        Insert: {
          body_markdown: string
          category?: string | null
          created_at?: string
          created_by?: string | null
          excerpt: string
          id?: string
          image_briefs?: Json
          internal_links?: Json
          job_id: string
          meta_description?: string | null
          meta_title?: string | null
          origin?: Database["public"]["Enums"]["draft_origin"]
          parent_draft_id?: string | null
          prompt_template_id?: string | null
          prompt_version?: number | null
          provider_run_id?: string | null
          research_packet_id: string
          responds_to_audit_id?: string | null
          review_note?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          schema_version: string
          slug: string
          source_refs?: Json
          title: string
          validation_errors?: Json | null
          validation_status: Database["public"]["Enums"]["artifact_validation"]
          version: number
        }
        Update: {
          body_markdown?: string
          category?: string | null
          created_at?: string
          created_by?: string | null
          excerpt?: string
          id?: string
          image_briefs?: Json
          internal_links?: Json
          job_id?: string
          meta_description?: string | null
          meta_title?: string | null
          origin?: Database["public"]["Enums"]["draft_origin"]
          parent_draft_id?: string | null
          prompt_template_id?: string | null
          prompt_version?: number | null
          provider_run_id?: string | null
          research_packet_id?: string
          responds_to_audit_id?: string | null
          review_note?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          schema_version?: string
          slug?: string
          source_refs?: Json
          title?: string
          validation_errors?: Json | null
          validation_status?: Database["public"]["Enums"]["artifact_validation"]
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: "drafts_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "article_jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "drafts_parent_draft_id_job_id_fkey"
            columns: ["parent_draft_id", "job_id"]
            isOneToOne: false
            referencedRelation: "drafts"
            referencedColumns: ["id", "job_id"]
          },
          {
            foreignKeyName: "drafts_prompt_template_id_fkey"
            columns: ["prompt_template_id"]
            isOneToOne: false
            referencedRelation: "prompt_templates"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "drafts_provider_run_id_job_id_fkey"
            columns: ["provider_run_id", "job_id"]
            isOneToOne: false
            referencedRelation: "provider_runs"
            referencedColumns: ["id", "job_id"]
          },
          {
            foreignKeyName: "drafts_research_packet_id_job_id_fkey"
            columns: ["research_packet_id", "job_id"]
            isOneToOne: false
            referencedRelation: "research_packets"
            referencedColumns: ["id", "job_id"]
          },
          {
            foreignKeyName: "drafts_responds_to_audit_id_job_id_fkey"
            columns: ["responds_to_audit_id", "job_id"]
            isOneToOne: false
            referencedRelation: "audits"
            referencedColumns: ["id", "job_id"]
          },
        ]
      }
      images: {
        Row: {
          alt_text: string | null
          aspect_ratio: string
          byte_size: number | null
          caption: string | null
          content_hash: string | null
          created_at: string
          focal_x: number | null
          focal_y: number | null
          height: number | null
          id: string
          job_id: string
          mime_type: string | null
          private_path: string | null
          prompt: string | null
          provider_run_id: string | null
          public_path: string | null
          published_at: string | null
          purpose: string | null
          review_note: string | null
          reviewed_at: string | null
          reviewed_by: string | null
          role: Database["public"]["Enums"]["image_role"]
          slot: number
          status: Database["public"]["Enums"]["image_status"]
          version: number
          width: number | null
        }
        Insert: {
          alt_text?: string | null
          aspect_ratio: string
          byte_size?: number | null
          caption?: string | null
          content_hash?: string | null
          created_at?: string
          focal_x?: number | null
          focal_y?: number | null
          height?: number | null
          id?: string
          job_id: string
          mime_type?: string | null
          private_path?: string | null
          prompt?: string | null
          provider_run_id?: string | null
          public_path?: string | null
          published_at?: string | null
          purpose?: string | null
          review_note?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          role: Database["public"]["Enums"]["image_role"]
          slot: number
          status?: Database["public"]["Enums"]["image_status"]
          version: number
          width?: number | null
        }
        Update: {
          alt_text?: string | null
          aspect_ratio?: string
          byte_size?: number | null
          caption?: string | null
          content_hash?: string | null
          created_at?: string
          focal_x?: number | null
          focal_y?: number | null
          height?: number | null
          id?: string
          job_id?: string
          mime_type?: string | null
          private_path?: string | null
          prompt?: string | null
          provider_run_id?: string | null
          public_path?: string | null
          published_at?: string | null
          purpose?: string | null
          review_note?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          role?: Database["public"]["Enums"]["image_role"]
          slot?: number
          status?: Database["public"]["Enums"]["image_status"]
          version?: number
          width?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "images_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "article_jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "images_provider_run_id_job_id_fkey"
            columns: ["provider_run_id", "job_id"]
            isOneToOne: false
            referencedRelation: "provider_runs"
            referencedColumns: ["id", "job_id"]
          },
        ]
      }
      job_events: {
        Row: {
          actor_id: string | null
          actor_type: Database["public"]["Enums"]["actor_type"]
          created_at: string
          event_type: string
          from_status: Database["public"]["Enums"]["job_status"] | null
          id: number
          job_id: string
          lock_version: number | null
          metadata: Json
          note: string | null
          to_status: Database["public"]["Enums"]["job_status"] | null
        }
        Insert: {
          actor_id?: string | null
          actor_type: Database["public"]["Enums"]["actor_type"]
          created_at?: string
          event_type: string
          from_status?: Database["public"]["Enums"]["job_status"] | null
          id?: never
          job_id: string
          lock_version?: number | null
          metadata?: Json
          note?: string | null
          to_status?: Database["public"]["Enums"]["job_status"] | null
        }
        Update: {
          actor_id?: string | null
          actor_type?: Database["public"]["Enums"]["actor_type"]
          created_at?: string
          event_type?: string
          from_status?: Database["public"]["Enums"]["job_status"] | null
          id?: never
          job_id?: string
          lock_version?: number | null
          metadata?: Json
          note?: string | null
          to_status?: Database["public"]["Enums"]["job_status"] | null
        }
        Relationships: [
          {
            foreignKeyName: "job_events_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "article_jobs"
            referencedColumns: ["id"]
          },
        ]
      }
      originality_checks: {
        Row: {
          checker: string
          created_at: string
          draft_id: string
          id: string
          job_id: string
          matches: Json
          provider_run_id: string | null
          similarity_score: number | null
          status: Database["public"]["Enums"]["run_status"]
        }
        Insert: {
          checker: string
          created_at?: string
          draft_id: string
          id?: string
          job_id: string
          matches?: Json
          provider_run_id?: string | null
          similarity_score?: number | null
          status: Database["public"]["Enums"]["run_status"]
        }
        Update: {
          checker?: string
          created_at?: string
          draft_id?: string
          id?: string
          job_id?: string
          matches?: Json
          provider_run_id?: string | null
          similarity_score?: number | null
          status?: Database["public"]["Enums"]["run_status"]
        }
        Relationships: [
          {
            foreignKeyName: "originality_checks_draft_id_job_id_fkey"
            columns: ["draft_id", "job_id"]
            isOneToOne: false
            referencedRelation: "drafts"
            referencedColumns: ["id", "job_id"]
          },
          {
            foreignKeyName: "originality_checks_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "article_jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "originality_checks_provider_run_id_job_id_fkey"
            columns: ["provider_run_id", "job_id"]
            isOneToOne: false
            referencedRelation: "provider_runs"
            referencedColumns: ["id", "job_id"]
          },
        ]
      }
      prompt_templates: {
        Row: {
          content: string
          created_at: string
          created_by: string | null
          id: string
          is_active: boolean
          key: string
          notes: string | null
          site_id: string
          variables_schema: Json
          version: number
        }
        Insert: {
          content: string
          created_at?: string
          created_by?: string | null
          id?: string
          is_active?: boolean
          key: string
          notes?: string | null
          site_id: string
          variables_schema?: Json
          version: number
        }
        Update: {
          content?: string
          created_at?: string
          created_by?: string | null
          id?: string
          is_active?: boolean
          key?: string
          notes?: string | null
          site_id?: string
          variables_schema?: Json
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: "prompt_templates_site_id_fkey"
            columns: ["site_id"]
            isOneToOne: false
            referencedRelation: "sites"
            referencedColumns: ["id"]
          },
        ]
      }
      provider_runs: {
        Row: {
          attempt: number
          cost_amount: number | null
          cost_currency: string | null
          created_at: string
          cycle: number
          error_class: Database["public"]["Enums"]["error_class"] | null
          error_summary: string | null
          finished_at: string | null
          id: string
          idempotency_key: string
          input_refs: Json
          job_id: string
          mode: Database["public"]["Enums"]["provider_mode"]
          output_ref: Json | null
          prompt_snapshot: string | null
          prompt_template_id: string | null
          prompt_version: number | null
          provider: Database["public"]["Enums"]["provider_kind"]
          retryable: boolean | null
          schema_version: string
          stage: Database["public"]["Enums"]["pipeline_stage"]
          started_at: string
          status: Database["public"]["Enums"]["run_status"]
          usage: Json | null
          worker_id: string | null
        }
        Insert: {
          attempt?: number
          cost_amount?: number | null
          cost_currency?: string | null
          created_at?: string
          cycle?: number
          error_class?: Database["public"]["Enums"]["error_class"] | null
          error_summary?: string | null
          finished_at?: string | null
          id?: string
          idempotency_key: string
          input_refs?: Json
          job_id: string
          mode: Database["public"]["Enums"]["provider_mode"]
          output_ref?: Json | null
          prompt_snapshot?: string | null
          prompt_template_id?: string | null
          prompt_version?: number | null
          provider: Database["public"]["Enums"]["provider_kind"]
          retryable?: boolean | null
          schema_version: string
          stage: Database["public"]["Enums"]["pipeline_stage"]
          started_at?: string
          status?: Database["public"]["Enums"]["run_status"]
          usage?: Json | null
          worker_id?: string | null
        }
        Update: {
          attempt?: number
          cost_amount?: number | null
          cost_currency?: string | null
          created_at?: string
          cycle?: number
          error_class?: Database["public"]["Enums"]["error_class"] | null
          error_summary?: string | null
          finished_at?: string | null
          id?: string
          idempotency_key?: string
          input_refs?: Json
          job_id?: string
          mode?: Database["public"]["Enums"]["provider_mode"]
          output_ref?: Json | null
          prompt_snapshot?: string | null
          prompt_template_id?: string | null
          prompt_version?: number | null
          provider?: Database["public"]["Enums"]["provider_kind"]
          retryable?: boolean | null
          schema_version?: string
          stage?: Database["public"]["Enums"]["pipeline_stage"]
          started_at?: string
          status?: Database["public"]["Enums"]["run_status"]
          usage?: Json | null
          worker_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "provider_runs_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "article_jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "provider_runs_prompt_template_id_fkey"
            columns: ["prompt_template_id"]
            isOneToOne: false
            referencedRelation: "prompt_templates"
            referencedColumns: ["id"]
          },
        ]
      }
      provider_settings: {
        Row: {
          api_mode_confirmed_at: string | null
          api_mode_confirmed_by: string | null
          created_at: string
          id: string
          mode: Database["public"]["Enums"]["provider_mode"]
          settings: Json
          site_id: string
          stage: Database["public"]["Enums"]["pipeline_stage"]
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          api_mode_confirmed_at?: string | null
          api_mode_confirmed_by?: string | null
          created_at?: string
          id?: string
          mode: Database["public"]["Enums"]["provider_mode"]
          settings?: Json
          site_id: string
          stage: Database["public"]["Enums"]["pipeline_stage"]
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          api_mode_confirmed_at?: string | null
          api_mode_confirmed_by?: string | null
          created_at?: string
          id?: string
          mode?: Database["public"]["Enums"]["provider_mode"]
          settings?: Json
          site_id?: string
          stage?: Database["public"]["Enums"]["pipeline_stage"]
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "provider_settings_site_id_fkey"
            columns: ["site_id"]
            isOneToOne: false
            referencedRelation: "sites"
            referencedColumns: ["id"]
          },
        ]
      }
      publishing_logs: {
        Row: {
          article_id: string | null
          attempt: number
          check_name: string | null
          created_at: string
          duration_ms: number | null
          error: string | null
          http_status: number | null
          id: number
          job_id: string
          kind: Database["public"]["Enums"]["publish_log_kind"]
          outcome: Database["public"]["Enums"]["log_outcome"]
          request_summary: Json
          result_summary: Json
          worker_id: string | null
        }
        Insert: {
          article_id?: string | null
          attempt?: number
          check_name?: string | null
          created_at?: string
          duration_ms?: number | null
          error?: string | null
          http_status?: number | null
          id?: never
          job_id: string
          kind: Database["public"]["Enums"]["publish_log_kind"]
          outcome: Database["public"]["Enums"]["log_outcome"]
          request_summary?: Json
          result_summary?: Json
          worker_id?: string | null
        }
        Update: {
          article_id?: string | null
          attempt?: number
          check_name?: string | null
          created_at?: string
          duration_ms?: number | null
          error?: string | null
          http_status?: number | null
          id?: never
          job_id?: string
          kind?: Database["public"]["Enums"]["publish_log_kind"]
          outcome?: Database["public"]["Enums"]["log_outcome"]
          request_summary?: Json
          result_summary?: Json
          worker_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "publishing_logs_article_id_fkey"
            columns: ["article_id"]
            isOneToOne: false
            referencedRelation: "articles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "publishing_logs_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "article_jobs"
            referencedColumns: ["id"]
          },
        ]
      }
      research_packets: {
        Row: {
          created_at: string
          id: string
          job_id: string
          packet: Json
          prompt_template_id: string | null
          prompt_version: number | null
          provider_run_id: string | null
          review_note: string | null
          reviewed_at: string | null
          reviewed_by: string | null
          schema_version: string
          summary: string | null
          validation_errors: Json | null
          validation_status: Database["public"]["Enums"]["artifact_validation"]
          version: number
        }
        Insert: {
          created_at?: string
          id?: string
          job_id: string
          packet: Json
          prompt_template_id?: string | null
          prompt_version?: number | null
          provider_run_id?: string | null
          review_note?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          schema_version: string
          summary?: string | null
          validation_errors?: Json | null
          validation_status: Database["public"]["Enums"]["artifact_validation"]
          version: number
        }
        Update: {
          created_at?: string
          id?: string
          job_id?: string
          packet?: Json
          prompt_template_id?: string | null
          prompt_version?: number | null
          provider_run_id?: string | null
          review_note?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          schema_version?: string
          summary?: string | null
          validation_errors?: Json | null
          validation_status?: Database["public"]["Enums"]["artifact_validation"]
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: "research_packets_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "article_jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "research_packets_prompt_template_id_fkey"
            columns: ["prompt_template_id"]
            isOneToOne: false
            referencedRelation: "prompt_templates"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "research_packets_provider_run_id_job_id_fkey"
            columns: ["provider_run_id", "job_id"]
            isOneToOne: false
            referencedRelation: "provider_runs"
            referencedColumns: ["id", "job_id"]
          },
        ]
      }
      site_settings: {
        Row: {
          auto_publish_default: boolean
          created_at: string
          default_byline_name: string
          default_byline_role: string | null
          editorial_contact_email: string | null
          extra: Json
          seo_default_description: string | null
          seo_default_title: string | null
          share_image_path: string | null
          site_id: string
          style_guide_template_id: string | null
          updated_at: string
          updated_by: string | null
          worker_offline_after_seconds: number
          worker_stale_after_seconds: number
        }
        Insert: {
          auto_publish_default?: boolean
          created_at?: string
          default_byline_name?: string
          default_byline_role?: string | null
          editorial_contact_email?: string | null
          extra?: Json
          seo_default_description?: string | null
          seo_default_title?: string | null
          share_image_path?: string | null
          site_id: string
          style_guide_template_id?: string | null
          updated_at?: string
          updated_by?: string | null
          worker_offline_after_seconds?: number
          worker_stale_after_seconds?: number
        }
        Update: {
          auto_publish_default?: boolean
          created_at?: string
          default_byline_name?: string
          default_byline_role?: string | null
          editorial_contact_email?: string | null
          extra?: Json
          seo_default_description?: string | null
          seo_default_title?: string | null
          share_image_path?: string | null
          site_id?: string
          style_guide_template_id?: string | null
          updated_at?: string
          updated_by?: string | null
          worker_offline_after_seconds?: number
          worker_stale_after_seconds?: number
        }
        Relationships: [
          {
            foreignKeyName: "site_settings_site_id_fkey"
            columns: ["site_id"]
            isOneToOne: true
            referencedRelation: "sites"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "site_settings_style_guide_template_id_fkey"
            columns: ["style_guide_template_id"]
            isOneToOne: false
            referencedRelation: "prompt_templates"
            referencedColumns: ["id"]
          },
        ]
      }
      sites: {
        Row: {
          canonical_origin: string
          created_at: string
          currency: string
          description: string
          disclosure: string
          id: string
          locale: string
          name: string
          slug: string
          timezone: string
          updated_at: string
        }
        Insert: {
          canonical_origin: string
          created_at?: string
          currency?: string
          description?: string
          disclosure?: string
          id?: string
          locale?: string
          name: string
          slug: string
          timezone?: string
          updated_at?: string
        }
        Update: {
          canonical_origin?: string
          created_at?: string
          currency?: string
          description?: string
          disclosure?: string
          id?: string
          locale?: string
          name?: string
          slug?: string
          timezone?: string
          updated_at?: string
        }
        Relationships: []
      }
      sources: {
        Row: {
          accessed_at: string
          content_hash: string | null
          created_at: string
          excerpt: string | null
          id: string
          is_private: boolean
          job_id: string
          jurisdiction: string | null
          published_on: string | null
          publisher: string | null
          quality: Database["public"]["Enums"]["source_quality"]
          research_packet_id: string
          source_key: string
          source_type: Database["public"]["Enums"]["source_type"]
          title: string
          url: string
        }
        Insert: {
          accessed_at: string
          content_hash?: string | null
          created_at?: string
          excerpt?: string | null
          id?: string
          is_private?: boolean
          job_id: string
          jurisdiction?: string | null
          published_on?: string | null
          publisher?: string | null
          quality?: Database["public"]["Enums"]["source_quality"]
          research_packet_id: string
          source_key: string
          source_type?: Database["public"]["Enums"]["source_type"]
          title: string
          url: string
        }
        Update: {
          accessed_at?: string
          content_hash?: string | null
          created_at?: string
          excerpt?: string | null
          id?: string
          is_private?: boolean
          job_id?: string
          jurisdiction?: string | null
          published_on?: string | null
          publisher?: string | null
          quality?: Database["public"]["Enums"]["source_quality"]
          research_packet_id?: string
          source_key?: string
          source_type?: Database["public"]["Enums"]["source_type"]
          title?: string
          url?: string
        }
        Relationships: [
          {
            foreignKeyName: "sources_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "article_jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sources_research_packet_id_job_id_fkey"
            columns: ["research_packet_id", "job_id"]
            isOneToOne: false
            referencedRelation: "research_packets"
            referencedColumns: ["id", "job_id"]
          },
        ]
      }
      worker_instances: {
        Row: {
          created_at: string
          current_job_id: string | null
          current_stage: Database["public"]["Enums"]["pipeline_stage"] | null
          health: Json
          host_label: string | null
          last_seen_at: string
          started_at: string
          version: string | null
          worker_id: string
        }
        Insert: {
          created_at?: string
          current_job_id?: string | null
          current_stage?: Database["public"]["Enums"]["pipeline_stage"] | null
          health?: Json
          host_label?: string | null
          last_seen_at?: string
          started_at?: string
          version?: string | null
          worker_id: string
        }
        Update: {
          created_at?: string
          current_job_id?: string | null
          current_stage?: Database["public"]["Enums"]["pipeline_stage"] | null
          health?: Json
          host_label?: string | null
          last_seen_at?: string
          started_at?: string
          version?: string | null
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "worker_instances_current_job_id_fkey"
            columns: ["current_job_id"]
            isOneToOne: false
            referencedRelation: "article_jobs"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      admin_activate_prompt_template: {
        Args: { p_template_id: string }
        Returns: {
          key: string
          template_id: string
          version: number
        }[]
      }
      admin_complete_manual_images: {
        Args: { p_job_id: string; p_run_id: string }
        Returns: Database["public"]["Enums"]["job_status"]
      }
      admin_create_prompt_version: {
        Args: {
          p_activate?: boolean
          p_content: string
          p_key: string
          p_notes?: string
          p_variables_schema?: Json
        }
        Returns: {
          is_active: boolean
          template_id: string
          version: number
        }[]
      }
      admin_dashboard: { Args: { p_list_limit?: number }; Returns: Json }
      admin_import_manual_image: {
        Args: {
          p_byte_size: number
          p_content_hash: string
          p_height: number
          p_job_id: string
          p_metadata: Json
          p_mime_type: string
          p_private_path: string
          p_run_id: string
          p_slot: number
          p_width: number
        }
        Returns: {
          image_id: string
          image_version: number
        }[]
      }
      admin_import_manual_result: {
        Args: { p_job_id: string; p_output: Json; p_run_id: string }
        Returns: {
          artifact_id: string
          artifact_version: number
          imported_stage: Database["public"]["Enums"]["pipeline_stage"]
          job_status: Database["public"]["Enums"]["job_status"]
        }[]
      }
      admin_transition_job: {
        Args: {
          p_action: string
          p_desired_publish_at?: string
          p_expected_lock_version: number
          p_job_id: string
          p_note?: string
          p_to_status?: Database["public"]["Enums"]["job_status"]
        }
        Returns: {
          lock_version: number
          status: Database["public"]["Enums"]["job_status"]
        }[]
      }
      admin_update_provider_setting: {
        Args: {
          p_confirm_api: boolean
          p_mode: Database["public"]["Enums"]["provider_mode"]
          p_stage: Database["public"]["Enums"]["pipeline_stage"]
        }
        Returns: {
          updated_mode: Database["public"]["Enums"]["provider_mode"]
          updated_stage: Database["public"]["Enums"]["pipeline_stage"]
        }[]
      }
      admin_update_site_identity: {
        Args: {
          p_description: string
          p_disclosure: string
          p_name: string
          p_timezone: string
        }
        Returns: Json
      }
      admin_update_site_settings: {
        Args: {
          p_auto_publish_default: boolean
          p_default_byline_name: string
          p_default_byline_role: string
          p_editorial_contact_email: string
          p_seo_default_description: string
          p_seo_default_title: string
          p_share_image_path: string
          p_worker_offline_after_seconds: number
          p_worker_stale_after_seconds: number
        }
        Returns: Json
      }
      claim_next_job: {
        Args: {
          p_lease_seconds?: number
          p_stages?: Database["public"]["Enums"]["pipeline_stage"][]
          p_worker_id: string
        }
        Returns: {
          attempt: number
          job_id: string
          lease_expires_at: string
          lease_token: string
          lock_version: number
          mode: Database["public"]["Enums"]["provider_mode"]
          revision_count: number
          stage: Database["public"]["Enums"]["pipeline_stage"]
          status: Database["public"]["Enums"]["job_status"]
        }[]
      }
      complete_stage: {
        Args: {
          p_job_id: string
          p_lease_token: string
          p_metadata?: Json
          p_note?: string
          p_to_status: Database["public"]["Enums"]["job_status"]
          p_worker_id: string
        }
        Returns: Database["public"]["Enums"]["job_status"]
      }
      create_article_job: {
        Args: {
          p_article_type?: Database["public"]["Enums"]["article_type"]
          p_audit_mode?: Database["public"]["Enums"]["provider_mode"]
          p_auto_publish?: boolean
          p_category?: string
          p_desired_publish_at?: string
          p_image_count?: number
          p_images_mode?: Database["public"]["Enums"]["provider_mode"]
          p_keywords?: string[]
          p_requirements?: string
          p_research_mode?: Database["public"]["Enums"]["provider_mode"]
          p_target_word_count?: number
          p_topic: string
          p_writing_mode?: Database["public"]["Enums"]["provider_mode"]
        }
        Returns: string
      }
      fail_stage: {
        Args: {
          p_error_class: Database["public"]["Enums"]["error_class"]
          p_job_id: string
          p_lease_token: string
          p_outcome: string
          p_retry_at?: string
          p_run_id?: string
          p_summary: string
          p_worker_id: string
        }
        Returns: Database["public"]["Enums"]["job_status"]
      }
      heartbeat_worker: {
        Args: {
          p_current_job_id?: string
          p_current_stage?: Database["public"]["Enums"]["pipeline_stage"]
          p_health?: Json
          p_host_label?: string
          p_started_at?: string
          p_version?: string
          p_worker_id: string
        }
        Returns: string
      }
      publish_article: {
        Args: {
          p_job_id: string
          p_lease_token: string
          p_published_images?: Json
          p_worker_id: string
        }
        Returns: {
          article_id: string
          canonical_url: string
          published_at: string
          slug: string
        }[]
      }
      record_revalidation: {
        Args: {
          p_attempts?: number
          p_duration_ms?: number
          p_error?: string
          p_http_status?: number
          p_job_id: string
          p_outcome: Database["public"]["Enums"]["log_outcome"]
          p_request_summary?: Json
          p_worker_id: string
        }
        Returns: number
      }
      record_verification: {
        Args: {
          p_checks: Json
          p_job_id: string
          p_lease_token: string
          p_retry_at?: string
          p_worker_id: string
        }
        Returns: Database["public"]["Enums"]["job_status"]
      }
      recover_expired_leases: { Args: never; Returns: number }
      renew_lease: {
        Args: {
          p_job_id: string
          p_lease_seconds?: number
          p_lease_token: string
          p_worker_id: string
        }
        Returns: string
      }
      request_manual_action: {
        Args: {
          p_job_id: string
          p_lease_token: string
          p_message: string
          p_run_id: string
          p_worker_id: string
        }
        Returns: Database["public"]["Enums"]["job_status"]
      }
      worker_status: { Args: { p_worker_id: string }; Returns: Json }
    }
    Enums: {
      action_required_kind:
        | "manual_input"
        | "cli_auth"
        | "usage_limit"
        | "invalid_output"
        | "editorial_review"
        | "publish_conflict"
        | "verification_failed"
      actor_type: "system" | "worker" | "admin"
      admin_role: "owner" | "editor" | "viewer"
      article_status: "published" | "verified" | "withdrawn"
      article_type:
        | "news"
        | "analysis"
        | "explainer"
        | "guide"
        | "company"
        | "interview"
      artifact_validation: "valid" | "invalid"
      audit_verdict: "PASS" | "REVISION_REQUIRED" | "NEEDS_HUMAN"
      claim_status: "unverified" | "supported" | "contradicted" | "mixed"
      draft_origin: "provider" | "admin_edit"
      error_class:
        | "transient"
        | "rate_limit"
        | "usage_limit"
        | "auth"
        | "invalid_output"
        | "permanent_config"
        | "unknown"
      evidence_relation: "supports" | "contradicts" | "context"
      image_role: "hero" | "supporting"
      image_status: "briefed" | "uploaded" | "ready" | "published" | "rejected"
      job_status:
        | "IDEA"
        | "RESEARCH_PENDING"
        | "RESEARCHING"
        | "RESEARCH_COMPLETE"
        | "DRAFT_PENDING"
        | "DRAFTING"
        | "DRAFT_COMPLETE"
        | "IMAGES_PENDING"
        | "IMAGES_PROCESSING"
        | "AUDIT_PENDING"
        | "AUDITING"
        | "REVISION_REQUIRED"
        | "REVISING"
        | "RE_AUDIT_PENDING"
        | "APPROVED"
        | "SCHEDULED"
        | "PUBLISHING"
        | "PUBLISHED"
        | "VERIFIED"
        | "PAUSED"
        | "FAILED"
        | "NEEDS_HUMAN"
      log_outcome: "succeeded" | "failed" | "skipped"
      pipeline_stage:
        | "research"
        | "draft"
        | "images"
        | "audit"
        | "revision"
        | "publish"
        | "verify"
      provider_kind: "openai" | "anthropic" | "gemini" | "internal"
      provider_mode:
        | "mock"
        | "manual_chatgpt"
        | "codex_cli"
        | "openai_api"
        | "claude_code"
        | "manual_claude"
        | "anthropic_api"
        | "manual_gemini"
        | "gemini_api"
        | "internal"
      publish_log_kind:
        | "publish"
        | "revalidate"
        | "verify_check"
        | "verify_summary"
      run_status:
        | "running"
        | "action_required"
        | "succeeded"
        | "failed"
        | "cancelled"
      source_quality: "primary" | "secondary" | "tertiary"
      source_type:
        | "regulator"
        | "government"
        | "central_bank"
        | "legislation"
        | "company_filing"
        | "company"
        | "statistics"
        | "academic"
        | "news"
        | "other"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      action_required_kind: [
        "manual_input",
        "cli_auth",
        "usage_limit",
        "invalid_output",
        "editorial_review",
        "publish_conflict",
        "verification_failed",
      ],
      actor_type: ["system", "worker", "admin"],
      admin_role: ["owner", "editor", "viewer"],
      article_status: ["published", "verified", "withdrawn"],
      article_type: [
        "news",
        "analysis",
        "explainer",
        "guide",
        "company",
        "interview",
      ],
      artifact_validation: ["valid", "invalid"],
      audit_verdict: ["PASS", "REVISION_REQUIRED", "NEEDS_HUMAN"],
      claim_status: ["unverified", "supported", "contradicted", "mixed"],
      draft_origin: ["provider", "admin_edit"],
      error_class: [
        "transient",
        "rate_limit",
        "usage_limit",
        "auth",
        "invalid_output",
        "permanent_config",
        "unknown",
      ],
      evidence_relation: ["supports", "contradicts", "context"],
      image_role: ["hero", "supporting"],
      image_status: ["briefed", "uploaded", "ready", "published", "rejected"],
      job_status: [
        "IDEA",
        "RESEARCH_PENDING",
        "RESEARCHING",
        "RESEARCH_COMPLETE",
        "DRAFT_PENDING",
        "DRAFTING",
        "DRAFT_COMPLETE",
        "IMAGES_PENDING",
        "IMAGES_PROCESSING",
        "AUDIT_PENDING",
        "AUDITING",
        "REVISION_REQUIRED",
        "REVISING",
        "RE_AUDIT_PENDING",
        "APPROVED",
        "SCHEDULED",
        "PUBLISHING",
        "PUBLISHED",
        "VERIFIED",
        "PAUSED",
        "FAILED",
        "NEEDS_HUMAN",
      ],
      log_outcome: ["succeeded", "failed", "skipped"],
      pipeline_stage: [
        "research",
        "draft",
        "images",
        "audit",
        "revision",
        "publish",
        "verify",
      ],
      provider_kind: ["openai", "anthropic", "gemini", "internal"],
      provider_mode: [
        "mock",
        "manual_chatgpt",
        "codex_cli",
        "openai_api",
        "claude_code",
        "manual_claude",
        "anthropic_api",
        "manual_gemini",
        "gemini_api",
        "internal",
      ],
      publish_log_kind: [
        "publish",
        "revalidate",
        "verify_check",
        "verify_summary",
      ],
      run_status: [
        "running",
        "action_required",
        "succeeded",
        "failed",
        "cancelled",
      ],
      source_quality: ["primary", "secondary", "tertiary"],
      source_type: [
        "regulator",
        "government",
        "central_bank",
        "legislation",
        "company_filing",
        "company",
        "statistics",
        "academic",
        "news",
        "other",
      ],
    },
  },
} as const

