import {
  draftOutputSchema,
  type AuditOutput,
  type DraftOutput,
  type ResearchPacketOutput,
} from "../../contracts/artifacts.js";
import {
  idempotencyKeyFor,
  renderTemplate,
  type ExecuteRequest,
  type PreparedRun,
  type RawRunResult,
  type RunContext,
  type StageAdapter,
} from "../contract.js";
import { Deterministic, slugToken } from "./deterministic.js";
import { MockStageError, mockNote, runDirectives } from "./shared.js";

/**
 * Deterministic drafting and revision for the mock pipeline.
 *
 * Both stages produce a complete draft: the revision stage is the drafting stage given an audit,
 * which is exactly how the real Claude adapter will work (plan section 11, "the result is always a
 * new draft version"). The body is real Markdown with real structure so the public renderer, the
 * audit stage, and the design review all have something honest to work with, and it closes with a
 * standing note that the text is simulated.
 */

export type DraftStageInput = Readonly<{
  packet: ResearchPacketOutput;
  /** Present on a revision: the draft being revised and the audit it must answer. */
  previous?: Readonly<{ draft: DraftOutput; audit: AuditOutput }> | undefined;
}>;

const CLOSING_SECTION =
  "## About this draft\n\n" +
  "This article was generated by FinTechPulse's mock provider while the editorial pipeline was " +
  "being exercised. It contains no verified reporting and should not be published to readers.";

function titleCaseFirst(value: string): string {
  const trimmed = value.trim();
  return trimmed.length === 0 ? trimmed : trimmed[0]!.toUpperCase() + trimmed.slice(1);
}

function truncate(value: string, maximum: number): string {
  return value.length <= maximum ? value : `${value.slice(0, maximum - 1).trimEnd()}…`;
}

function sourceList(packet: ResearchPacketOutput): string {
  return packet.sources
    .map((source) => `- [${source.title}](${source.url}) — ${source.publisher ?? "Publisher"}`)
    .join("\n");
}

function sectionBody(
  heading: string,
  packet: ResearchPacketOutput,
  random: Deterministic,
  subject: string,
): string {
  const claim = random.pick(packet.claims);
  const fact = random.pick(packet.facts);
  const source = random.pick(packet.sources);

  return [
    `## ${heading}`,
    "",
    `${titleCaseFirst(fact)} For ${subject}, that is the part most firms will feel first.`,
    "",
    `${titleCaseFirst(claim.text)} ${
      claim.status === "mixed"
        ? "The published sources do not agree on this point, and the difference is material."
        : claim.status === "unverified"
          ? "This figure is indicative: no official impact assessment has been located."
          : `The ${source.publisher ?? "regulator"} sets this out in its published material.`
    }`,
    "",
  ].join("\n");
}

function buildBody(
  packet: ResearchPacketOutput,
  random: Deterministic,
  subject: string,
  targetWordCount: number | null,
): string {
  const sections = packet.recommendedStructure.slice(
    0,
    targetWordCount !== null && targetWordCount < 700 ? 3 : packet.recommendedStructure.length,
  );

  const opening = [
    `${titleCaseFirst(packet.angle)} This is what is actually changing, who it applies to in the ` +
      `United Kingdom, and what is still unresolved.`,
    "",
    `${titleCaseFirst(packet.topicInterpretation)}`,
    "",
  ].join("\n");

  const body = sections
    .map((heading) => sectionBody(heading, packet, random, subject))
    .join("\n")
    .trimEnd();

  const openQuestions = [
    "",
    "",
    "## What is still open",
    "",
    ...packet.uncertainties.map((uncertainty) => `- ${uncertainty}`),
    "",
    packet.contradictions.length > 0
      ? `Two published sources give different answers here. ${packet.contradictions[0]}`
      : "No source conflicts were identified during research.",
    "",
    "## Where the official detail lives",
    "",
    sourceList(packet),
    "",
    "FinTechPulse publishes general editorial information, not personalised financial, investment, " +
      "tax, credit, insurance, or legal advice.",
    "",
    CLOSING_SECTION,
  ].join("\n");

  return `${opening}${body}${openQuestions}\n`;
}

/** Builds the draft. Exported so the deterministic output can be asserted without a database. */
export function buildDraft(context: RunContext, input: DraftStageInput): DraftOutput {
  const { brief } = context;
  const packet = input.packet;
  const revisionOf = input.previous;
  const random = new Deterministic(brief.jobId, "draft", context.cycle);
  const subject = brief.topic.trim();
  const token = slugToken(subject, 60);

  const baseTitle = truncate(
    `${titleCaseFirst(subject)}: what UK firms need to know`,
    revisionOf ? 200 : 200,
  );
  const title = revisionOf?.draft.title ?? baseTitle;
  const slug = revisionOf?.draft.slug ?? token;

  const body = buildBody(packet, random, subject, brief.targetWordCount);
  const revisedBody = revisionOf
    ? [
        body.trimEnd(),
        "",
        "## Corrections made in revision",
        "",
        ...revisionOf.audit.findings.map(
          (finding) =>
            `- ${finding.category} (${finding.severity}): ${finding.recommendedCorrection}`,
        ),
        "",
      ].join("\n")
    : body;

  const imageBriefs = Array.from({ length: brief.imageCount }, (_, slot) => ({
    slot,
    role: slot === 0 ? ("hero" as const) : ("supporting" as const),
    purpose:
      slot === 0
        ? `Lead image for an article about ${subject}.`
        : `Supporting image for section ${slot} of an article about ${subject}.`,
    prompt:
      `Restrained editorial photograph in a British setting, natural light, near-neutral palette, ` +
      `no text, no logos, no people identifiable. Subject: ${subject}.`,
    altText:
      slot === 0
        ? `A calm, document-led editorial scene standing in for coverage of ${subject}.`
        : `A secondary editorial scene supporting the section on ${subject}.`,
    aspectRatio: slot === 0 ? ("16:9" as const) : ("3:2" as const),
  }));

  const draft = {
    title,
    slug,
    excerpt: truncate(`${titleCaseFirst(packet.angle)} ${mockNote()}`, 500),
    bodyMarkdown: revisedBody,
    metaTitle: truncate(title, 70),
    metaDescription: truncate(packet.angle, 320),
    category: brief.category,
    internalLinks: [
      {
        href: "/blog",
        label: "More FinTechPulse coverage",
        reason: "Archive index, always present.",
      },
    ],
    imageBriefs,
    // The publication source list is built from these keys, so only public sources are referenced.
    sourceReferences: packet.sources
      .filter((source) => !source.isPrivate)
      .map((source) => source.sourceKey),
  };

  return draftOutputSchema.parse(draft);
}

abstract class MockDraftingAdapter implements StageAdapter<DraftStageInput, DraftOutput> {
  abstract readonly stage: "draft" | "revision";
  readonly mode = "mock" as const;
  readonly provider = "anthropic" as const;

  protected abstract templateVariables(
    input: DraftStageInput,
    context: RunContext,
  ): Record<string, string>;

  async prepare(input: DraftStageInput, context: RunContext): Promise<PreparedRun> {
    const { brief } = context;
    const prompt = context.template
      ? renderTemplate(context.template.content, {
          styleGuide: context.styleGuide ?? "",
          topic: brief.topic,
          articleType: brief.articleType,
          category: brief.category ?? "unset",
          keywords: brief.keywords.join(", "),
          targetWordCount: String(brief.targetWordCount ?? "unset"),
          imageCount: String(brief.imageCount),
          requirements: brief.requirements ?? "none",
          cycle: String(context.cycle),
          today: brief.today,
          schemaVersion: context.schemaVersion,
          ...this.templateVariables(input, context),
        })
      : `Write a UK fintech article about: ${brief.topic}`;

    return {
      prompt,
      promptTemplateId: context.template?.id ?? null,
      promptVersion: context.template?.version ?? null,
      inputRefs: {
        sources: input.packet.sources.length,
        claims: input.packet.claims.length,
        image_briefs: brief.imageCount,
        ...(input.previous ? { findings: input.previous.audit.findings.length } : {}),
      },
      schemaVersion: context.schemaVersion,
      provider: this.provider,
      mode: this.mode,
      idempotencyKey: idempotencyKeyFor(this.stage, context),
    };
  }

  async execute(request: ExecuteRequest<DraftStageInput>): Promise<RawRunResult> {
    const directed = await runDirectives(this.stage, request);
    if (directed) return directed;
    return {
      kind: "output",
      value: buildDraft(request.context, request.input),
      usage: { simulated: true },
    };
  }

  async normalize(raw: RawRunResult, context: RunContext): Promise<DraftOutput> {
    void context;
    if (raw.kind !== "output") {
      throw new MockStageError(`the ${this.stage} stage produced no output`, "invalid_output");
    }
    return draftOutputSchema.parse(raw.value);
  }
}

export class MockDraftAdapter extends MockDraftingAdapter {
  override readonly stage = "draft" as const;

  protected override templateVariables(input: DraftStageInput): Record<string, string> {
    return { researchPacket: JSON.stringify(input.packet, null, 2) };
  }
}

export class MockRevisionAdapter extends MockDraftingAdapter {
  override readonly stage = "revision" as const;

  protected override templateVariables(input: DraftStageInput): Record<string, string> {
    return {
      researchPacket: JSON.stringify(input.packet, null, 2),
      draft: JSON.stringify(input.previous?.draft ?? null, null, 2),
      auditFindings: JSON.stringify(input.previous?.audit.findings ?? [], null, 2),
    };
  }
}
